version: '3.1'

services:
  app:
    image: 'bb1942ef5591202fb98d9c38c6d5000796fc61c5856deec34ede320c9476fc14'
    container_name: app
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_URL=jdbc:postgresql://db:5432/postgres
    depends_on:
      - db
  db:
    image: 'postgres'
    container_name: db
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres